# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    container_name: backend
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    container_name: frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
